In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv(r"C:\Users\7719s\Desktop\ai_class\week5\kc_house_data.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [3]:
print(df.dtypes)

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [4]:
df['date'] = pd.to_datetime(df['date'], format='%Y%m%dT%H%M%S')
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df = df.drop(columns=['id', 'date'])
print(df.dtypes)

price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
year               int32
month              int32
day                int32
dtype: object

In [5]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,year,month,day
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,...,1955,0,98178,47.5112,-122.257,1340,5650,2014,10,13
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,...,1951,1991,98125,47.7210,-122.319,1690,7639,2014,12,9
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,...,1933,0,98028,47.7379,-122.233,2720,8062,2015,2,25
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,...,1965,0,98136,47.5208,-122.393,1360,5000,2014,12,9
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,...,1987,0,98074,47.6168,-122.045,1800,7503,2015,2,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,...,2009,0,98103,47.6993,-122.346,1530,1509,2014,5,21
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,...,2014,0,98146,47.5107,-122.362,1830,7200,2015,2,23
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,...,2009,0,98144,47.5944,-122.299,1020,2007,2014,6,23
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,...,2004,0,98027,47.5345,-122.069,1410,1287,2015,1,16
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,...,2008,0,98144,47.5941,-122.299,1020,1357,2014,10,15

In [6]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'year', 'month', 'day'],
      dtype='object')

In [7]:
df.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
year             0
month            0
day              0
dtype: int64

In [8]:
X = df.drop('price', axis=1)
y=df['price']
y.value_counts()

price
350000.0     172
450000.0     172
550000.0     159
500000.0     152
425000.0     150
            ...
607010.0       1
1362500.0      1
298800.0       1
957500.0       1
402101.0       1
Name: count, Length: 4028, dtype: int64

In [9]:
print(X.dtypes)

bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
year               int32
month              int32
day                int32
dtype: object

In [10]:
X = X.values # 딥러닝 입력을 위해 numpy로 변환

In [11]:
# 6. 데이터 스케일링 (특히 딥러닝 모델은 스케일된 데이터에서 잘 동작함)
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [12]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.15/0.85, random_state=42)

In [13]:
# 컬럼갯수 확인
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(X_val.shape, y_val.shape)

(15129, 21) (15129,)
(3242, 21) (3242,)
(3242, 21) (3242,)

In [14]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import tensorflow as tf
from tensorflow import keras


model = Sequential()

model.add(Dense(20,input_shape=(X_test.shape[1],),activation='relu')) # 입력층 최소 입력이랑 갯수 똑같게
model.add(Dense(30,activation='relu')) # 히든층
model.add(Dense(20,activation='relu')) # 히든층
model.add(Dense(1)) # 출력층  출력이랑 갯수 똑같게
#히든층은 마름모꼴 구조로 만드는걸 교수님은 추천 혹은 피라미드 구조
# 회귀 문제라서 loss funciton mse 및 출력층 None
model.compile(optimizer='adam',loss='mse',metrics=['mae'])
# 회귀문제라서 metrics(평가지표)를 mae(예측값과 실제값 사이 평균오차)로 사용

model.summary()

C:\Users\7719s\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 20)                  │             440 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │             630 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 20)                  │             620 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              21 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,711 (6.68 KB)

 Trainable params: 1,711 (6.68 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model_history = model.fit(x=X_train, y=y_train, epochs=30, batch_size=32, validation_data=(X_val, y_val))
y_pred = model.predict(X_test)

Epoch 1/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 415431852032.0000 - mae: 537220.1250 - val_loss: 398200569856.0000 - val_mae: 522848.0625
Epoch 2/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - loss: 345073319936.0000 - mae: 493553.6875 - val_loss: 180175880192.0000 - val_mae: 339908.6875
Epoch 3/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - loss: 138399105024.0000 - mae: 288274.6875 - val_loss: 71900577792.0000 - val_mae: 198529.2812
Epoch 4/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - loss: 69232492544.0000 - mae: 193854.2812 - val_loss: 58288230400.0000 - val_mae: 174688.3906
Epoch 5/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - loss: 59817459712.0000 - mae: 177494.6094 - val_loss: 52650741760.0000 - val_mae: 164222.2344
Epoch 6/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - loss: 54553874432.0000 - mae: 166233.2031 - val_loss: 48563826688.0000 - val_mae: 155630.3750
Epoch 7/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - loss: 49485819904.0000 - mae: 158544.8906 - val_loss: 45245739008.0000 - val_mae: 147387.4688
Epoch 8/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - loss: 46249730048.0000 - mae: 149186.0312 - val_loss: 42319982592.0000 - val_mae: 140143.7969
Epoch 9/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 42919661568.0000 - mae: 141412.6562 - val_loss: 39849074688.0000 - val_mae: 133862.1875
Epoch 10/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - loss: 41086578688.0000 - mae: 135572.6250 - val_loss: 37886255104.0000 - val_mae: 128078.6016
Epoch 11/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - loss: 37712474112.0000 - mae: 130569.9922 - val_loss: 36250783744.0000 - val_mae: 123476.8750
Epoch 12/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - loss: 38580912128.0000 - mae: 126632.0156 - val_loss: 35081195520.0000 - val_mae: 119513.0391
Epoch 13/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - loss: 36279717888.0000 - mae: 121995.7734 - val_loss: 33946173440.0000 - val_mae: 117923.2578
Epoch 14/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - loss: 32881528832.0000 - mae: 116924.1875 - val_loss: 33091631104.0000 - val_mae: 115349.0547
Epoch 15/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - loss: 36648669184.0000 - mae: 119094.7188 - val_loss: 32447655936.0000 - val_mae: 113409.6875
Epoch 16/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - loss: 32546781184.0000 - mae: 114647.6328 - val_loss: 31911385088.0000 - val_mae: 112438.2656
Epoch 17/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - loss: 33049446400.0000 - mae: 114767.3359 - val_loss: 31496415232.0000 - val_mae: 111220.4688
Epoch 18/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 31799955456.0000 - mae: 113228.7188 - val_loss: 31184310272.0000 - val_mae: 110328.6562
Epoch 19/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 32482994176.0000 - mae: 112641.4922 - val_loss: 30893191168.0000 - val_mae: 109550.9922
Epoch 20/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - loss: 31660736512.0000 - mae: 113077.3750 - val_loss: 30691782656.0000 - val_mae: 109810.2734
Epoch 21/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 31567636480.0000 - mae: 111066.5547 - val_loss: 30474024960.0000 - val_mae: 108488.0859
Epoch 22/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 32645220352.0000 - mae: 111982.9531 - val_loss: 30286063616.0000 - val_mae: 108282.9766
Epoch 23/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 32140498944.0000 - mae: 111224.0234 - val_loss: 30168037376.0000 - val_mae: 107328.8203
Epoch 24/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 33689569280.0000 - mae: 112278.6094 - val_loss: 29989353472.0000 - val_mae: 108080.8203
Epoch 25/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 29933182976.0000 - mae: 109833.6797 - val_loss: 29849348096.0000 - val_mae: 107437.3281
Epoch 26/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - loss: 33468125184.0000 - mae: 111287.0234 - val_loss: 29769900032.0000 - val_mae: 106744.4219
Epoch 27/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - loss: 31852797952.0000 - mae: 110727.1016 - val_loss: 29657993216.0000 - val_mae: 106463.3125
Epoch 28/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - loss: 31911514112.0000 - mae: 110309.7891 - val_loss: 29535809536.0000 - val_mae: 107039.5469
Epoch 29/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - loss: 34282743808.0000 - mae: 109783.3281 - val_loss: 29453434880.0000 - val_mae: 106271.5938
Epoch 30/30
473/473 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - loss: 29308952576.0000 - mae: 107260.5625 - val_loss: 29360984064.0000 - val_mae: 106298.8359
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step

In [16]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# y_test: 실제값, y_pred: 모델 예측값
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("MAE:", mae)
print("R² Score:", r2)

MSE: 37152019872.25927
MAE: 112765.94548359423
R² Score: 0.7565706293660879